version: "3.9"
services:
    frontend:
        image: frontend
        container_name: frontend
        build:
            context: ./frontend
        networks: 
            - frontend
            - backend
        ports:
            - "80:80"
    backend:
        image: api
        container_name: api
        build:
            context: ./api
        networks: 
            - backend
        ports:
            - "8080:8080"
networks: 
  frontend:
  backend: