services:

  frontend:
    image: frontend
    build:
      context: ./frontend
    depends_on:
      - api
    networks:
      - public
    ports:
      - 80:80

  gateway:
    image: gateway
    build:
      context: ./gateway
    networks:
      - public
      - private
    ports:
      - 8080:8080

  discovery-server:
    image: discovery-server
    build:
      context: ./discovery-server
    networks:
      - private
    ports:
      - 8761:8761

  api:
    image: api
    build:
      context: ./api
    depends_on:
      - db
    networks:
      - private
      - monitoring
    ports:
      - 8090:8090

  db:
    image: db
    build:
      context: ./db
    networks:
      - private
    ports:
      - 3306:3306

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

volumes:
  prometheus_data: {}

networks:
  public:
  private:
  monitoring: