server:
 port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
        - env
        - health
        - info
        - prometheus
        - metrics
  
spring:
 application:
  name: gateway
 cloud:
  gateway:
    default-filters:
    - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
    globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
    routes:
    - id: api
      uri: lb://api
      predicates:
       - Path=/api/v1/hotels/**