DROP TABLE IF EXISTS hotel;

CREATE TABLE hotel (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(250) NOT NULL,
    price BIGINT NOT NULL,
    PRIMARY KEY (id)
);