server.port=8090

management.endpoints.web.exposure.include=env,health,info,prometheus,metrics

# Eureka configuration
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${random.value}

spring.datasource.url=jdbc:mysql://db:3306/api?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Disable old SQL scripts
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

# Liquibase configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.mvc.problemdetails.enabled=true
